In [8]:
import numpy as np

In [9]:
a=np.array([2, 1, 0])
b=np.array([0, 1, 2])

In [18]:
#叉乘
c=np.cross(a,b)
c

array([ 2, -4,  2])

In [31]:
#点积
d=np.dot(a,b)
d

1

In [16]:
#点乘
d=np.multiply(a,b)
d

array([0, 1, 0])

In [26]:
a.T

array([2, 1, 0])

In [29]:
f=a.T*b
f

array([0, 1, 0])